export interface VenEstModel {
  VE_CODIGO: number,
  VE_VALOR: number,
  VE_QUANTIDADE: number,
  VE_VEN: number,
  VE_PRO: number,
  VE_LUCRO?: number,
  VE_VALORR?: number,
  VE_VALORL?: number,
  VE_VALORF?: number,
  VE_DIFERENCA?: number,
  VE_LIQUIDO?: number,
  VE_VALOR2?: number,
  VE_VALORCM?: number,
  VE_GTIN?: string,
  VE_EMBALAGEM?: string,
  VE_VALORB?: number,
  VE_DESCONTO?: number,
  VE_VALORC?: number,
  VE_ALIQUOTA?: number,
  VE_NOME: string,
  VE_SEMENTE_TRATADA?: string,
  VE_ESTADO?: string
}