/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/pioEt7dp1Om
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { useEffect, useState } from "react"
import { ClienteModel, Fidelidade, Situacao, TipoPessoa } from "@/app/models/cliente_model"
import { GeraCodigo, mascaraMoedaEvent, maskRealToNumber } from "@/app/functions/utils"
import { InputMask, useMask } from '@react-input/mask';




export function Cadastro_clientes() {

  const [cliente, setCliente] = useState<ClienteModel>({CODIGO:0, NOME:''})
  const [ehCpf, setEhCpf] = useState(true);
  const [valorLimiteAux, setvalorLimiteAux] = useState('');

  const inputRefCpf = useMask({ mask: '___.___.___-__', replacement: { _: /\d/ } });
  const inputRefCnpj = useMask({ mask: '__.___.___/____-__', replacement: { _: /\d/ } });
  const inputRefCep = useMask({ mask: '_____-___', replacement: { _: /\d/ } });
  const inputRefFone = useMask({ mask: '(__)_____-____', replacement: { _: /\d/ } });
  useEffect(()=>{
    inicializaCliente();
  }, [])

  
  useEffect(()=>{
    cliente.TIPO == TipoPessoa.FISICA ? setEhCpf(true) : setEhCpf(false);
    console.log(cliente.NOME);
  }, [cliente])

  useEffect(() => {
    const valor = maskRealToNumber(valorLimiteAux);
    setCliente({ ...cliente, LIMITE: valor ? valor : 0 })
}, [valorLimiteAux]);

  async function inicializaCliente(){
    let cod = await GeraCodigo('CLIENTES', 'CLI_CODIGO');
    setCliente({...cliente, CODIGO:cod, TIPO: TipoPessoa.FISICA,
       FIDELIDADE:Fidelidade.NENHUMA});
  }

  return (
    <div className="overflow-scroll">
    <div className="p-4 sm:w-[800px] sm:h-96">
      <div className="border rounded-md p-4 space-y-4">
        <h2 className="text-xl font-bold">Cadastro de Clientes</h2>        
        <div className="grid grid-cols-2 gap-4">
          <div className="col-span-2">
            <h3 className="text-lg font-semibold">Dados Gerais</h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="codigo">Código</Label>
                <Input id="codigo" disabled={true} defaultValue={cliente.CODIGO} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="tipo">Tipo</Label>
                <Select value={cliente.TIPO}  onValueChange={(e) => setCliente({...cliente, TIPO:e})} >
                  <SelectTrigger id="tipo">
                    <SelectValue placeholder="Jurídica" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value={TipoPessoa.FISICA}>Física</SelectItem>
                    <SelectItem value={TipoPessoa.JURIDICA}>Jurídica</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="cpf_cnpj">CPF/CNPJ</Label>
                <Input ref={ehCpf ? inputRefCpf : inputRefCnpj}
                placeholder={ehCpf ? 'Digite seu CPF' : 'Digite seu CNPJ'}
                value={cliente.CPF_CNPJ}
                onChange={(e) => setCliente({...cliente, CPF_CNPJ:e.target.value})}
                />
                
              </div>
              <div className="space-y-2">
                <Label htmlFor="rg">RG</Label>
                <Input id="rg" value={cliente.RG} onChange={(e) => setCliente({...cliente, RG:e.target.value})} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="nome_fantasia">Nome (Fantasia)</Label>
                <Input id="nome_fantasia" value={cliente.NOME}
                 onChange={(e) => setCliente({...cliente, NOME:e.target.value})} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="razao_social">Razão Social</Label>
                <Input id="razao_social" value={cliente.RAZAOSOCIAL}
                 onChange={(e) => setCliente({...cliente, RAZAOSOCIAL:e.target.value})} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="endereco">Endereço</Label>
                <Input id="endereco" value={cliente.ENDERECO}
                 onChange={(e) => setCliente({...cliente, ENDERECO:e.target.value})} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="numero">Número</Label>
                <Input id="numero" value={cliente.NUMERO} type="number"
                 onChange={(e) => setCliente({...cliente, NUMERO:e.target.value})} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="bairro">Bairro</Label>
                <Input id="bairro" value={cliente.BAIRRO}
                 onChange={(e) => setCliente({...cliente, BAIRRO:e.target.value})} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="cidade">Cidade</Label>
                <Input id="numero" value={cliente.CIDADE}
                 onChange={(e) => setCliente({...cliente, CIDADE:e.target.value})} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="cep">CEP</Label>
                <Input ref={inputRefCep}
                value={cliente.CEP}
                onChange={(e) => setCliente({...cliente, CEP:e.target.value})}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="fone">Fone</Label>
                <Input ref={inputRefFone}
                value={cliente.FONE}
                onChange={(e) => setCliente({...cliente, FONE:e.target.value})}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="fidelidade">Fidelidade</Label>
                <Select value={cliente.FIDELIDADE}  onValueChange={(e) => setCliente({...cliente, FIDELIDADE:e as Fidelidade})}>
                  <SelectTrigger id="fidelidade">
                    <SelectValue placeholder={cliente.FIDELIDADE} />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value={Fidelidade.NENHUMA}>Nenhuma</SelectItem>
                    <SelectItem value={Fidelidade.RUIM}>Ruim</SelectItem>
                    <SelectItem value={Fidelidade.REGULAR}>Regular</SelectItem>
                    <SelectItem value={Fidelidade.BOM}>Bom</SelectItem>
                    <SelectItem value={Fidelidade.OTIMO}>Otimo</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="inadimplencia">Inadimplência</Label>
                <Input id="inadiplencia" value={cliente.INADIPLENCIA} type="number"
                 onChange={(e) => setCliente({...cliente, INADIPLENCIA:parseInt(e.target.value)})} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="desconto">Desconto</Label>
                <Input id="desconto" value={cliente.DESCONTO} type="number"
                 onChange={(e) => setCliente({...cliente, DESCONTO:parseInt(e.target.value)})} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="situacao">Situação</Label>
                <Select value={cliente.SITUACAO}  onValueChange={(e) => setCliente({...cliente, SITUACAO:e as Situacao})}>
                  <SelectTrigger id="situacao">
                    <SelectValue placeholder="Livre" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value={Situacao.LIVRE}>Livre</SelectItem>
                    <SelectItem value={Situacao.OBSERVACAO}>Observação</SelectItem>
                    <SelectItem value={Situacao.BLOQUEADO}>Bloqueado</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="limite">Limite</Label>
                <Input id="edtValorProduto" value={valorLimiteAux?? ''} onChange={event => { mascaraMoedaEvent(event), setvalorLimiteAux(event.target.value) }} className="uppercase p-1 border rounded-md border-spacing-1 border-amber-400" type="text" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="data_nasc">Data Nasc</Label>
                <Input id="data_nasc" type="date" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="pai">Pai</Label>
                <Input id="pai" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="mae">Mãe</Label>
                <Input id="mae" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="conjuge">Cônjuge</Label>
                <Input id="conjuge" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="insc_estadual">Indicador da Insc. Estadual</Label>
                <Select>
                  <SelectTrigger id="insc_estadual">
                    <SelectValue placeholder="9" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="1">1</SelectItem>
                    <SelectItem value="2">2</SelectItem>
                    <SelectItem value="3">3</SelectItem>
                    <SelectItem value="4">4</SelectItem>
                    <SelectItem value="5">5</SelectItem>
                    <SelectItem value="6">6</SelectItem>
                    <SelectItem value="7">7</SelectItem>
                    <SelectItem value="8">8</SelectItem>
                    <SelectItem value="9">9</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="insc_estadual_num">Inscr. Estadual</Label>
                <Input id="insc_estadual_num" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="insc_municipal">Inscr. Munic.</Label>
                <Input id="insc_municipal" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="suframa">SUFRAMA</Label>
                <Input id="suframa" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="estado">Estado</Label>
                <Select>
                  <SelectTrigger id="estado">
                    <SelectValue placeholder="ATIVO" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="ativo">ATIVO</SelectItem>
                    <SelectItem value="inativo">INATIVO</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="data_cadastro">Data Cadastro</Label>
                <Input id="data_cadastro" type="date" defaultValue="2024-06-18" />
              </div>
            </div>
          </div>          
        </div>
        <div className="border-t pt-4">
          <h3 className="text-lg font-semibold">Dados Adicionais</h3>
          <div className="grid grid-cols-3 gap-4">
            <div className="space-y-2">
              <Label htmlFor="email">E-Mail</Label>
              <Input id="email" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="celular">Celular</Label>
              <Input id="celular" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="tipo_pgm">Tipo Pgm</Label>
              <Select>
                <SelectTrigger id="tipo_pgm">
                  <SelectValue placeholder="1 - Pedido" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="1">1 - Pedido</SelectItem>
                  <SelectItem value="2">2 - Consulta</SelectItem>
                  <SelectItem value="3">3 - Outros</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="cadastro">Cadastro</Label>
              <Input id="cadastro" type="date" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="data_ultima_compra">Data Última Compra</Label>
              <Input id="data_ultima_compra" type="date" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="desconto_adicional">Desconto</Label>
              <Select>
                <SelectTrigger id="desconto_adicional">
                  <SelectValue placeholder="SIM" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="sim">SIM</SelectItem>
                  <SelectItem value="nao">NÃO</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="endereco_corresp">Endereço Corresp.</Label>
              <Input id="endereco_corresp" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="bairro_corresp">Bairro Corresp.</Label>
              <Input id="bairro_corresp" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="cidade_corresp">Cidade Corresp.</Label>
              <Input id="cidade_corresp" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="limite_titulo">Limite Titulo</Label>
              <Input id="limite_titulo" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="tipo_entr">Tipo Entr.</Label>
              <Select>
                <SelectTrigger id="tipo_entr">
                  <SelectValue placeholder="1 - Retirado" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="1">1 - Retirado</SelectItem>
                  <SelectItem value="2">2 - Entregue</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="vencimento">Vencimento</Label>
              <Input id="vencimento" type="date" defaultValue="1900-01-01" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="validade_cartao">Validade do Cartão</Label>
              <Input id="validade_cartao" />
            </div>
            <div className="col-span-3 space-y-2">
              <Label htmlFor="observacao">Observação</Label>
              <Textarea id="observacao" />
            </div>
          </div>
        </div>
      </div>
      <div className="text-sm mt-4">
        <p>
        <div className="bg-white shadow-lg p-4">
            <div className="flex justify-around space-x-2">
              <Button variant="outline" className="flex-1">
                Inserir
              </Button>
              <Button variant="destructive" className="flex-1">
                Excluir
              </Button>
              <Button variant="default" className="flex-1">
                Confirmar
              </Button>
              <Button variant="outline" className="flex-1">
                Cancelar
              </Button>
              <Button variant="secondary" className="flex-1">
                Editar
              </Button>              
            </div>
          </div>
        </p>
      </div>
    </div>
    </div>
  )
}
